Mobile menu
wuletawwonte/mobile-menu pull request #1
Opened 2022-06-23 06:54 UTC by wuletawwonte

changes in this pr
- implement the following features:
- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

2022-06-24 14:13 UTC, sumairq requested changes
Hi @wuletawwonte , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️Nice Summary 
✔️Good commit history
✔️Interactive elements are working perfectly

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 14:13 UTC, sumairq commented on index.html
>        <h1 id="logo">Aziz Mejri</h1>
- [ ] Your logo should be inside `a` tag instead of the `h1` tag. It is part of accessibility best practices to ensure that logo is a clickable link that leads to the homepage.

2022-06-25 03:30 UTC, sumairq commented on README.md
> +# Mobile Menu
- [ ] Let's add proper documentation within the readme file, right now it is missing the crucial information about the project. A README file is a guide that gives users a detailed description of the project you have worked on. 😃 
 
### It's missing the following sections:
 🏗️ **Built With** 
  it should showcase the tech stack used in the project.
🖥️ **Live Demo** (if available) 
  should contain a link leading to live version.
✏️ **Getting Started**  
    Usually, it should have instructions on how to install and 
     run the project.
 🥇**Authors**    
   This section should include the social handles of the contributors to the project.
🤝 **Contributing**
 This section is meant to welcome contributors.
**Acknowledgments**
**License**
 
 You can refer to this [template](https://github.com/microverseinc/readme-template) for guidance.

2022-06-25 11:59 UTC, mirouhml requested changes
Hi @wuletawwonte, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of what was requested, but there are still some which aren't addressed yet, but don't worry you're almost there 😁!

![](https://media4.giphy.com/media/840zvMIuYv3ZwXanfN/giphy.gif?cid=ecf05e47ghaxqowuanp9qqavc012wmgfw5fvf253ljz9npuf&rid=giphy.gif&ct=g)

 ## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 
- Meaningful commit messages ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-25 11:59 UTC, mirouhml commented on README.md
> +- etc
## [OPTIONAL]

I think that If you don't have anything to share in the acknowledgments section you can remove it 🧐🧐, and add it later when you want to share something related.

2022-06-25 11:59 UTC, mirouhml commented on index.html
> +        <a href="/" id="logo">Aziz Mejri</a>
Good job changing the logo to a link 🥳, please know that as the previous reviewer mentioned, the `a` tag needs to be inside an `h1` tag, right now there is no `h1` tag.

The logo also needs a bit more styling now, right now it looks like this:

<img src="https://user-images.githubusercontent.com/20567503/175770802-472715fb-a9da-4098-91c6-1ceec1d55c6e.png" width="300">

And according to the design it should look like this:

<img src="https://user-images.githubusercontent.com/20567503/175770793-7b544078-f6a6-457b-bb7d-c55204ce13bd.png" width="300">

Hint 😉: you can remove the hyperlink styling using this line `text-decoration: none;`

2022-06-25 11:59 UTC, mirouhml commented on index.html
> +          <li><a href="#contact-me" onclick="menuLink()"> Contact </a></li>
## [OPTIONAL]

Please know that the function you're mentioning here: `onclick="menuLink()"` doesn't exist in the js file 🙃🙃, and this caused two things, the mobile menu doesn't disappear when you click on a menu item and the following error in the console:
![image](https://user-images.githubusercontent.com/20567503/175771566-89d1f75c-e003-46f0-b915-0a96a01bcccf.png)

I suggest you implement it so that it hides the menu when the user clicks on a mobile menu item, this should fix the error on the console as well 😉.

Also, please know that the links `Portfolio` and `Contact` have the wrong id in the `href` attribute, the `Portfolio` one should be `href="#projects"` and the `Contact` should be `href="#contact"`.

After fixing everything your menu should work as expected 😎😎

2023-07-17 09:11 UTC, merged